name: untitled
version: 1.0.0+1
publish_to: none
description: A new Flutter project.

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  google_fonts: ^2.3.1

  collection: ^1.15.0

  get: 4.6.1
  get_cli: ^1.7.1
  get_storage: ^2.0.2

  dio: ^4.0.0
  pretty_dio_logger: ^1.1.1
  retrofit: ^3.0.1+1
  easy_debounce: ^2.0.2+1

  intl: ^0.17.0
  timeago: ^3.2.1
  recase: ^4.0.0
  easy_localization:
    path: easy_localization-3.0.0

  cupertino_icons: ^1.0.2
  flutter_font_icons: ^2.2.4
  badges: ^2.0.2

  firebase_core: ^1.12.0
  firebase_messaging: ^11.2.6

  flutter_native_splash: ^2.0.4
  flutter_platform_widgets: ^1.12.1
  flutter_local_notifications: ^9.3.2
  flutter_custom_clippers: ^2.0.0
  flutter_bloc: ^8.0.1
  flutter_screenutil: ^5.3.1


  package_info_plus: ^1.3.0
  device_info_plus: ^3.2.1
  #  wait until flutter local notification is updated to be compatible with
  #  connectivity_plus: ^2.2.1

  percent_indicator: ^4.0.0
  smooth_page_indicator: ^1.0.0+2
  loading_indicator: ^3.0.2
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1

  shimmer: ^2.0.0
  fancy_shimmer_image: ^2.0.1+1
  show_up_animation: ^2.0.0
  transformer_page_view_tv: any

  expandable: ^5.0.1
  sliding_up_panel: ^2.0.0+1
  sliver_tools: ^0.2.5
  flutter_group_sliver:
    git: https://github.com/Ali1Ammar/flutter_group_sliver


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  flutter_launcher_icons: ^0.9.2

  retrofit_generator: ^4.0.1
  build_runner: ^2.1.7
  json_serializable: ^6.1.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/locale/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
          weight: 100

    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-Italic.ttf
          weight: 400
          style: italic

    - family: Patrick
      fonts:
        - asset: assets/fonts/PatrickHand-Regular.ttf

    - family: Bebas
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf

    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-Thin.ttf
          weight: 100
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato-Italic.ttf
          weight: 400
          style: italic


flutter_native_splash:
  color: '#ffffff'
  color_dark: '#0c1a30'
  image: 'assets/images/splash.png'
  image_dark: 'assets/images/splash.png'


flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  remove_alpha_ios: true
